version: '2'
services:
  nginx:
    image: lalyos/rpi-nginx
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /etc/nginx/conf.d

  nginx-proxy:
    image: bengosney/nginx-proxy-rpi
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
